branches:
  only:
    - release

language: python

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - hugo

deploy:
  - provider: pages
    skip_cleanup: true
    github-token: "$GITHUB_TOKEN"
    local-dir: public
    target-branch: master
    keep-history: true
    on:
      branch: release
