baseURL: https://yoyodesign.github.io/developersblog/
enableGitInfo: true
enableRobotsTXT: true
languageCode: en-gb
paginate: 10
title: Yoyo developers blog
theme: yoyo-developers-blog

permalinks:
  post: /:filename/

params:
  description: Insight from the Yoyo development team.
  dateFormat: 2006-01-02

taxonomies:
  author: authors
  category: categories
  tag: tags
